name: run-tests
run-name: ${{ github.actor }} is running the tests
on: [push]
jobs:
  check-compatibility-for-php73:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          version: "2.2.x"
      - run: composer update
      - run: ./vendor/bin/phpunit --colors tests --do-not-cache-result
  check-compatibility-for-php82:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"
          version: "2.2.x"
      - run: ./vendor/bin/phpunit --colors tests --do-not-cache-result